### ISSUE TITLE
Mo Creatures compatibility

### ISSUE THREAD

**Issue by katubug** [pau101/Paint-This#2]
The horses from Dr Zharks mod aren't shearable. And because of the way they pseudo-overwrite the vanilla horses, it's almost impossible to acquire the hairs. Is there any way you could add compatibility? Or another creature to get the hair from? Or something? :P

**Comment by pau101** [comment]
The new version that adds this feature can be found [here](https://minecraft.curseforge.com/projects/paint-this/files/2323745).

**Comment by katubug** [comment]
Thanks immensely!
